### PR TITLE
Add simple option panel

### PR DESCRIPTION
**Pull request by skyghis**
A very simple option panel to choose list of files to add in project view.

Known Issue: 

I didn't find how to force reload of project view, so the project need to be closed and reopened after changing the value.

### CODE REVIEW

**Comment by Chris2011** [comment]
Great, thx :). Can you be so kind please and make a screenshot?

**Comment by skyghis** [comment]
image

**Comment by Chris2011** [comment]
Thx, will merge and test it in the next couple of days. No promise.

**Comment by Chris2011** [comment]
Maybe you can find the solution here: #1 @markiewb added a comment for that.

**Comment by Chris2011** [comment]
I'm on it to merge it and create a changelog and change the readme. Hope I will be finish with all in the next hours/couple of days. Stay tuned :)

**Pull request merged**
